# Generated by Django 4.2 on 2023-04-28 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='libros',
            name='isbn',
            field=models.CharField(default='', max_length=100),
        ),
    ]
